name: Build and Push Container Image on Release

on:
  release:
    types:
      - created
    branches:
      - Release
jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          IMAGE_TAG=$(echo "${GITHUB_REF#refs/tags/}" | tr / - | sed 's/-$//')
          docker build -f Dockerfile -t <username>/<service>:${IMAGE_TAG} .
          docker push <username>/<service>:${IMAGE_TAG}

